export const site = {
  name: "Toronto Deck Stainers",
  shortName: "Toronto Deck Stainers",
  phone: "(647) 478-7379",
  phoneHref: "tel:+16474787379",
  email: "sales@torontodeckstainers.ca",
  emailHref: "mailto:sales@torontodeckstainers.ca",
  address: {
    city: "Toronto",
    region: "ON",
    country: "CA",
  },
  addressLine: "Toronto, ON",
  hours: "Mon – Fri · 8 AM – 5 PM · Weekends Closed",
  yearsExperience: 15,
  url: "https://torontodeckstainers.ca",
  tagline: "GTA's Deck Restoration Experts Since 2008.",
  description:
    "Toronto's trusted deck staining, sealing, and restoration experts since 2008. Premium eco-friendly stains built to withstand Canadian winters — protecting your deck from freeze-thaw damage, UV fading, and spring moisture. Serving Toronto and all GTA.",
  serviceAreas: [
    "Toronto",
    "Richmond Hill",
    "Vaughan",
    "Markham",
    "Mississauga",
    "North York",
    "Scarborough",
    "Etobicoke",
    "Brampton",
    "Oakville",
    "Pickering",
  ],
  stats: {
    decksRestored: 1500,
    yearsInBusiness: 15,
    citiesServed: 9,
    rating: "5.0",
  },
  features: [
    "Licensed & fully insured",
    "Eco-friendly, low-VOC stains & sealers",
    "Free on-site estimates",
    "Engineered for Canadian freeze-thaw cycles",
    "Premium oil-based products with UV protection",
    "Satisfaction guaranteed on every project",
  ],
  trustBadges: [
    { label: "Decks Restored", value: "1,500+" },
    { label: "Years Experience", value: "15+" },
    { label: "GTA Cities Served", value: "9+" },
    { label: "Customer Rating", value: "5-Star" },
  ],
  responseTime: "24 hours",
} as const;
