export const site = {
  name: "GTA Christmas Lights",
  legalName: "GTA Christmas Lights",
  tagline: "Professional Christmas Light Installation Across the GTA",
  phone: "(416) 707-9994",
  phoneHref: "tel:+14167079994",
  phoneAlt: "(905) 707-9994",
  phoneAltHref: "tel:+19057079994",
  email: "info@gtachristmaslights.ca",
  emailHref: "mailto:info@gtachristmaslights.ca",
  address: {
    street: "Serving the Greater Toronto Area",
    city: "Vaughan",
    region: "ON",
    postal: "L4K 4K5",
    country: "CA",
  },
  addressLine: "Greater Toronto Area, Ontario",
  hours: "Monday–Friday · 9:00 AM – 6:00 PM",
  yearsExperience: 35,
  awardsCount: 3,
  startingPrice: 1500,
  serviceAreas: [
    "Toronto",
    "Vaughan",
    "Markham",
    "Richmond Hill",
    "Mississauga",
    "Oakville",
    "Brampton",
    "Aurora",
    "Newmarket",
    "King City",
    "Kleinburg",
    "Caledon",
    "Bradford",
    "Stouffville",
    "Whitby",
    "Thornhill",
    "Woodbridge",
    "North York",
    "Etobicoke",
    "Scarborough",
  ],
  url: "https://gtachristmaslights.ca",
  facebookUrl: "https://facebook.com/gtachristmaslights",
  instagramUrl: "https://instagram.com/gtachristmaslights",
  description:
    "Professional Christmas light installation, design, takedown, and storage across the Greater Toronto Area. 35+ years of experience, three Landscape Ontario Awards of Excellence, commercial-grade LED lighting, and a Hassle-Free Christmas Guarantee.",
} as const;
