export const site = {
  name: "GTA Christmas Lighting",
  legalName: "GTA Christmas Lighting",
  tagline: "Professional Christmas Light Installation Across the GTA",
  phone: "(289) 475-0433",
  phoneHref: "tel:+12894750433",
  phoneAlt: "(519) 266-6734",
  phoneAltHref: "tel:+15192666734",
  email: "info@gtachristmaslighting.ca",
  emailHref: "mailto:info@gtachristmaslighting.ca",
  address: {
    street: "Serving the Greater Toronto Area",
    city: "Toronto",
    region: "ON",
    postal: "",
    country: "CA",
  },
  addressLine: "Greater Toronto Area, Ontario",
  hours: "Mon–Sat · 8:00 AM – 8:00 PM · Oct 1 – Jan 31",
  startingPrice: 700,
  maxTypicalPrice: 2000,
  serviceAreas: [
    "Toronto",
    "Mississauga",
    "Brampton",
    "Vaughan",
    "Markham",
    "Richmond Hill",
    "Oakville",
    "Burlington",
    "Pickering",
    "Ajax",
    "Etobicoke",
    "North York",
    "Scarborough",
    "Georgetown",
  ],
  url: "https://gtachristmaslighting.ca",
  facebookUrl: "https://facebook.com/gtachristmaslighting",
  instagramUrl: "https://instagram.com/gtachristmaslighting",
  paymentMethods: ["Visa", "MasterCard", "American Express", "Cash", "Cheque"],
  season: "October 1 – January 31",
  description:
    "GTA's top-rated holiday lighting experts. Custom Christmas, holiday, and permanent light installations for homes and businesses across Toronto, Mississauga, Burlington, Oakville, Vaughan, Markham, and the rest of the Greater Toronto Area. Free quotes. Rental or purchase. Full-service: design, install, maintain, take down, store.",
} as const;
