export const site = {
  name: "Concrete Tilsonburg",
  shortName: "Concrete Tilsonburg",
  phone: "(519) 878-6735",
  phoneHref: "tel:+15198786735",
  email: "service@concretetilsonburg.ca",
  emailHref: "mailto:service@concretetilsonburg.ca",
  address: {
    city: "Tillsonburg",
    region: "ON",
    country: "CA",
  },
  addressLine: "Tillsonburg, ON",
  hours: "Mon – Fri · 8 AM – 5 PM · Weekends Closed",
  yearsExperience: 12,
  url: "https://concretetilsonburg.ca",
  tagline: "High-Strength Concrete Built for Ontario Winters.",
  description:
    "Oxford County's trusted concrete contractor specializing in custom driveways, stamped patios, structural repairs, and garage floors — engineered for harsh Southwestern Ontario freeze-thaw cycles.",
  serviceAreas: [
    "Tillsonburg",
    "Woodstock",
    "Delhi",
    "Ingersoll",
    "Simcoe",
    "Norwich",
    "Courtland",
    "Mount Elgin",
  ],
  stats: {
    projectsCompleted: 350,
    yearsInBusiness: 12,
    citiesServed: 15,
    satisfiedClients: 340,
  },
  features: [
    "Written warranty on every pour",
    "Engineered for Ontario freeze-thaw cycles",
    "Reinforced rebar + wire mesh standard",
    "Proper drainage and grading included",
    "Free on-site quote within 24 hours",
    "Fully insured + WSIB compliant",
  ],
  trustBadges: [
    { label: "Google Reviews", value: "4.9 / 5 Stars" },
    { label: "Years in Business", value: "12+ Years" },
    { label: "Projects Completed", value: "350+ Projects" },
    { label: "Warranty", value: "Written Guarantee" },
  ],
  responseTime: "4 business hours",
} as const;
