export const site = {
  name: "TriCity Concrete Sealing",
  shortName: "TriCity",
  phone: "(519) 902-0000",
  phoneHref: "tel:+15199020000",
  email: "service@tricityconcretesealing.ca",
  emailHref: "mailto:service@tricityconcretesealing.ca",
  address: {
    city: "London",
    region: "ON",
    country: "CA",
  },
  addressLine: "London, ON",
  hours: "Mon – Fri · 8 AM – 5 PM · Weekends Closed",
  yearsExperience: 8,
  url: "https://tricityconcretesealing.ca",
  tagline: "Protect and Beautify Your Concrete — Guaranteed.",
  description:
    "TriCity Concrete Sealing provides professional driveway, patio, stamped concrete, and walkway sealing across London, Woodstock, Brantford, and all of Southwestern Ontario. Backed by a 5-year warranty.",
  serviceAreas: [
    "London",
    "Woodstock",
    "Brantford",
    "St. Thomas",
    "Stratford",
    "Ingersoll",
    "Tillsonburg",
    "St. Marys",
    "Simcoe",
    "Aylmer",
  ],
  stats: {
    projectsCompleted: 500,
    yearsInBusiness: 8,
    citiesServed: 20,
    satisfiedClients: 480,
  },
  features: [
    "Industry-leading 5-year warranty",
    "Premium UV-resistant sealers",
    "Free site assessment & quote",
    "Fully insured & licensed",
    "Expert application — no lap marks or streaks",
    "Serving 20+ communities in SW Ontario",
  ],
  trustBadges: [
    { label: "Projects Sealed", value: "500+" },
    { label: "Years Experience", value: "8+ Yrs" },
    { label: "Warranty", value: "5 Years" },
    { label: "Google Rating", value: "4.9 / 5" },
  ],
  responseTime: "4 business hours",
  warrantyYears: 5,
} as const;
