export const site = {
  name: "TriCity Concrete Sealing",
  shortName: "TriCity",
  email: "service@tricityconcretesealing.ca",
  emailHref: "mailto:service@tricityconcretesealing.ca",
  address: {
    city: "London",
    region: "ON",
    country: "CA",
  },
  addressLine: "London, ON",
  hours: "Mon – Fri · 8 AM – 5 PM",
  hoursShort: "Mon–Fri 8–5",
  yearsExperience: 8,
  url: "https://tricityconcretesealing.ca",
  tagline: "Protect and Beautify Your Concrete — Guaranteed.",
  description:
    "TriCity Concrete Sealing applies high-quality solvent-based sealers in matte, semi-gloss and gloss finishes to driveways, patios, stamped concrete, walkways and exposed aggregate across London, Woodstock, Brantford and Southwestern Ontario. Backed by a 5-year workmanship warranty.",
  serviceAreas: [
    "London",
    "Woodstock",
    "Brantford",
    "St. Thomas",
    "Stratford",
    "Ingersoll",
    "Tillsonburg",
    "St. Marys",
    "Simcoe",
    "Aylmer",
  ],
  stats: {
    projectsCompleted: 500,
    yearsInBusiness: 8,
    citiesServed: 20,
    satisfiedClients: 480,
  },
  features: [
    "5-year workmanship warranty",
    "High-quality solvent-based sealers",
    "Matte, semi-gloss or gloss finish",
    "Free site assessment and quote",
    "Fully insured and licensed",
    "Sprayed and back-rolled, no lap marks",
  ],
  trustBadges: [
    { label: "500+ Projects", value: "Sealed across SW Ontario" },
    { label: "5-Year Warranty", value: "Written workmanship guarantee" },
    { label: "Solvent-Based Sealers", value: "Matte, semi-gloss or gloss" },
    { label: "Fully Insured", value: "Free site assessment" },
  ],
  responseTime: "4 business hours",
  warrantyYears: 5,
  googleRating: "4.9",
} as const;
