-- Kits
insert into public.readykitchens_kits (slug, name, tagline, shape, pieces, price_cad, layout_fits, wall_a_inches, wall_b_inches, wall_c_inches, island_inches, range_inches, fridge_inches, best_for, summary, hero_image, highlights, gallery, is_active) values
  ('kitchenette', 'The Kitchenette', '10-piece studio kitchen — fits one 10'' run', 'Single Wall', 10, 1950, 'Single 10-foot wall (120")', 120, null, null, null, 30, null, 'Basement apartments, garage suites, granny flats, office kitchenettes.', 'The most affordable way to drop in a complete kitchen along a single 10-foot wall. Sink, four base cabinets, full upper bank, and a 30" gap for a freestanding range + chimney hood (hood not included).', '/images/kits/kitchenette.jpg', '["Single 10-foot wall layout \u00e2\u20ac\u201d simplest install", "30\" range gap with open wall for a chimney hood", "33\" sink base + drawer bank for utensils", "Plywood boxes, soft-close doors and drawers"]'::jsonb, '["/images/kits/kitchenette.jpg"]'::jsonb, true)
on conflict (slug) do update set name=excluded.name, tagline=excluded.tagline, shape=excluded.shape, pieces=excluded.pieces, price_cad=excluded.price_cad, layout_fits=excluded.layout_fits, wall_a_inches=excluded.wall_a_inches, wall_b_inches=excluded.wall_b_inches, wall_c_inches=excluded.wall_c_inches, island_inches=excluded.island_inches, range_inches=excluded.range_inches, fridge_inches=excluded.fridge_inches, best_for=excluded.best_for, summary=excluded.summary, hero_image=excluded.hero_image, highlights=excluded.highlights, gallery=excluded.gallery, is_active=true, updated_at=now();
delete from public.readykitchens_kit_items where kit_slug='kitchenette';
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('kitchenette', 0, 'SB33', 1, 'Single or double-bowl sink');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('kitchenette', 1, 'DB18', 1, 'Utensils + cookware');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('kitchenette', 2, 'B12', 2, 'Spice or sheet pan storage');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('kitchenette', 3, 'B15', 1, 'Range-side base');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('kitchenette', 4, 'W1236', 2, 'Tall narrow uppers');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('kitchenette', 5, 'W1836', 1, 'Tall storage');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('kitchenette', 6, 'W2436', 2, 'Plates + bowls + dry goods');
insert into public.readykitchens_kits (slug, name, tagline, shape, pieces, price_cad, layout_fits, wall_a_inches, wall_b_inches, wall_c_inches, island_inches, range_inches, fridge_inches, best_for, summary, hero_image, highlights, gallery, is_active) values
  ('urban-starter', 'The Urban Starter', '12-piece galley kitchen — fits two 8'' runs', 'Galley', 12, 2900, 'Two opposing 8-foot walls (96" + 96")', 96, 96, null, null, 30, 36, 'Apartments, basement suites, secondary kitchens, rental flips.', 'A complete galley kitchen that drops into two opposing 8-foot walls. Sink + range on one wall, fridge bay + drawers on the other, plus over-fridge cabinet. 30" range gap is left open for a chimney hood (not included).', '/images/kits/urban-starter.jpg', '["Two opposing 8'' runs \u00e2\u20ac\u201d true galley layout", "30\" range gap with open wall for chimney hood", "Dedicated 30\" drawer base for pots and pans", "Over-fridge cabinet for top-shelf storage"]'::jsonb, '["/images/kits/urban-starter.jpg"]'::jsonb, true)
on conflict (slug) do update set name=excluded.name, tagline=excluded.tagline, shape=excluded.shape, pieces=excluded.pieces, price_cad=excluded.price_cad, layout_fits=excluded.layout_fits, wall_a_inches=excluded.wall_a_inches, wall_b_inches=excluded.wall_b_inches, wall_c_inches=excluded.wall_c_inches, island_inches=excluded.island_inches, range_inches=excluded.range_inches, fridge_inches=excluded.fridge_inches, best_for=excluded.best_for, summary=excluded.summary, hero_image=excluded.hero_image, highlights=excluded.highlights, gallery=excluded.gallery, is_active=true, updated_at=now();
delete from public.readykitchens_kit_items where kit_slug='urban-starter';
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('urban-starter', 0, 'SB36', 1, 'Wall 1 sink, double-bowl ready');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('urban-starter', 1, 'DB18', 1, 'Wall 1 — utensils');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('urban-starter', 2, 'B12', 2, 'Wall 1 + Wall 2 narrow bases');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('urban-starter', 3, 'DB30', 1, 'Wall 2 — pots and pans');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('urban-starter', 4, 'B18', 1, 'Wall 2 — base end');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('urban-starter', 5, 'W2436', 2, 'Wall 1 — over sink and drawer');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('urban-starter', 6, 'W1836', 1, 'Wall 1 — right of range');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('urban-starter', 7, 'W3036', 2, 'Wall 2 — over base run');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('urban-starter', 8, 'W361824', 1, 'Wall 2 — above fridge');
insert into public.readykitchens_kits (slug, name, tagline, shape, pieces, price_cad, layout_fits, wall_a_inches, wall_b_inches, wall_c_inches, island_inches, range_inches, fridge_inches, best_for, summary, hero_image, highlights, gallery, is_active) values
  ('modern-symmetrical', 'The Modern Symmetrical', '16-piece galley kitchen — fits two 10'' runs', 'Galley', 16, 3900, 'Two opposing 10-foot walls (120" + 120")', 120, 120, null, null, 30, 36, 'Family kitchens, mid-size remodels, balanced sink-and-stove layouts.', 'Balanced galley with sink + range on one 10'' wall and pantry + fridge + cooking on the other. 30" range gap leaves clean wall for a chimney hood (not included). Tall pantry tower included.', '/images/kits/modern-symmetrical.jpg', '["Twin 10'' runs \u00e2\u20ac\u201d balanced design", "Tall 24\" \u00c3\u2014 90\" pantry tower included", "30\" range gap with open wall for chimney hood", "Over-fridge cabinet for top-shelf storage"]'::jsonb, '["/images/kits/modern-symmetrical.jpg"]'::jsonb, true)
on conflict (slug) do update set name=excluded.name, tagline=excluded.tagline, shape=excluded.shape, pieces=excluded.pieces, price_cad=excluded.price_cad, layout_fits=excluded.layout_fits, wall_a_inches=excluded.wall_a_inches, wall_b_inches=excluded.wall_b_inches, wall_c_inches=excluded.wall_c_inches, island_inches=excluded.island_inches, range_inches=excluded.range_inches, fridge_inches=excluded.fridge_inches, best_for=excluded.best_for, summary=excluded.summary, hero_image=excluded.hero_image, highlights=excluded.highlights, gallery=excluded.gallery, is_active=true, updated_at=now();
delete from public.readykitchens_kit_items where kit_slug='modern-symmetrical';
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('modern-symmetrical', 0, 'SB33', 1, 'Wall 1 — sink');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('modern-symmetrical', 1, 'DB18', 1, 'Wall 1 — utensils');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('modern-symmetrical', 2, 'B12', 2, 'Wall 1 — narrow bases');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('modern-symmetrical', 3, 'B15', 1, 'Wall 1 — range-side end');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('modern-symmetrical', 4, 'W2436', 2, 'Wall 1 — over sink/drawer');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('modern-symmetrical', 5, 'W1236', 2, 'Wall 1 — over narrow bases');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('modern-symmetrical', 6, 'W1836', 1, 'Wall 1 — over range-side base');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('modern-symmetrical', 7, 'WP249024', 1, 'Wall 2 — full-height storage');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('modern-symmetrical', 8, 'DB30', 1, 'Wall 2 — pots and pans');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('modern-symmetrical', 9, 'B30', 1, 'Wall 2 — base run');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('modern-symmetrical', 10, 'W3036', 2, 'Wall 2 — over base run');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('modern-symmetrical', 11, 'W361824', 1, 'Wall 2 — above fridge');
insert into public.readykitchens_kits (slug, name, tagline, shape, pieces, price_cad, layout_fits, wall_a_inches, wall_b_inches, wall_c_inches, island_inches, range_inches, fridge_inches, best_for, summary, hero_image, highlights, gallery, is_active) values
  ('the-compact', 'The Compact', '14-piece L-shape — fits 8'' × 12'' corner', 'L-Shape', 14, 3900, 'L-shape, 8-foot leg × 12-foot leg', 96, 144, null, null, 30, 36, 'Open-concept kitchens, condos, additions, in-law suites.', 'Working L-shape with a lazy-susan corner that recovers every cubic inch. Range gap on the short leg, sink + fridge on the long leg. Chimney hood (not included) above the range; over-fridge cabinet above the fridge.', '/images/kits/the-compact.jpg', '["33\" lazy-susan corner \u00e2\u20ac\u201d fully usable corner space", "Wall diagonal-corner cabinet keeps uppers continuous", "30\" range gap with open wall for chimney hood", "Over-fridge cabinet included"]'::jsonb, '["/images/kits/the-compact.jpg"]'::jsonb, true)
on conflict (slug) do update set name=excluded.name, tagline=excluded.tagline, shape=excluded.shape, pieces=excluded.pieces, price_cad=excluded.price_cad, layout_fits=excluded.layout_fits, wall_a_inches=excluded.wall_a_inches, wall_b_inches=excluded.wall_b_inches, wall_c_inches=excluded.wall_c_inches, island_inches=excluded.island_inches, range_inches=excluded.range_inches, fridge_inches=excluded.fridge_inches, best_for=excluded.best_for, summary=excluded.summary, hero_image=excluded.hero_image, highlights=excluded.highlights, gallery=excluded.gallery, is_active=true, updated_at=now();
delete from public.readykitchens_kit_items where kit_slug='the-compact';
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('the-compact', 0, 'LS33', 1, 'Inside corner — rotating shelves');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('the-compact', 1, 'DB18', 2, 'Utensils — one per leg');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('the-compact', 2, 'B15', 1, 'Short leg — range-side');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('the-compact', 3, 'SB33', 1, 'Long leg — sink');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('the-compact', 4, 'B12', 2, 'Long leg — narrow bases');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('the-compact', 5, 'WDC2436', 1, 'Continuous corner uppers');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('the-compact', 6, 'W1836', 1, 'Short leg — over drawer');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('the-compact', 7, 'W1536', 2, 'Long leg — narrow uppers');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('the-compact', 8, 'W3036', 2, 'Long leg — over sink/drawer');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('the-compact', 9, 'W361824', 1, 'Long leg — above fridge');
insert into public.readykitchens_kits (slug, name, tagline, shape, pieces, price_cad, layout_fits, wall_a_inches, wall_b_inches, wall_c_inches, island_inches, range_inches, fridge_inches, best_for, summary, hero_image, highlights, gallery, is_active) values
  ('island-entertainer', 'The Island Entertainer', '23-piece L-shape + 10'' island', 'L-Shape + Island', 23, 6800, 'L-shape 12-foot × 14-foot with 10-foot island', 144, 168, null, 120, 30, 36, 'Hosting kitchens, open floor plans, full-home renovations.', 'Hosting-grade kitchen: a full L-shape perimeter with sink, range, fridge, and a 90" tall pantry, plus a 10-foot island with seating and drawers. 30" range gap left for a chimney hood (not included).', '/images/kits/island-entertainer.jpg', '["Full 24\" \u00c3\u2014 90\" tall pantry tower", "10-foot island \u00e2\u20ac\u201d seating + multiple drawer banks", "Lazy-susan corner + wall diagonal-corner", "30\" range gap with open wall for chimney hood"]'::jsonb, '["/images/kits/island-entertainer.jpg"]'::jsonb, true)
on conflict (slug) do update set name=excluded.name, tagline=excluded.tagline, shape=excluded.shape, pieces=excluded.pieces, price_cad=excluded.price_cad, layout_fits=excluded.layout_fits, wall_a_inches=excluded.wall_a_inches, wall_b_inches=excluded.wall_b_inches, wall_c_inches=excluded.wall_c_inches, island_inches=excluded.island_inches, range_inches=excluded.range_inches, fridge_inches=excluded.fridge_inches, best_for=excluded.best_for, summary=excluded.summary, hero_image=excluded.hero_image, highlights=excluded.highlights, gallery=excluded.gallery, is_active=true, updated_at=now();
delete from public.readykitchens_kit_items where kit_slug='island-entertainer';
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 0, 'LS33', 1, 'Inside corner');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 1, 'SB36', 1, 'Wall A — sink');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 2, 'DB18', 2, 'Wall A + Island');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 3, 'B12', 2, 'Wall A end + Island');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 4, 'B15', 2, 'Wall A + Wall B');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 5, 'WP249024', 1, 'Wall B — storage tower');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 6, 'DB30', 2, 'Wall B + Island');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 7, 'B30', 2, 'Wall B + Island');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 8, 'B18', 1, 'Island');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 9, 'WDC2436', 1, 'Continuous corner uppers');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 10, 'W3036', 5, 'Walls A + B — main uppers');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 11, 'W1536', 1, 'Wall B end');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 12, 'W361824', 1, 'Wall B — above fridge');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('island-entertainer', 13, 'WMC2736', 1, 'Built-in microwave nook');
insert into public.readykitchens_kits (slug, name, tagline, shape, pieces, price_cad, layout_fits, wall_a_inches, wall_b_inches, wall_c_inches, island_inches, range_inches, fridge_inches, best_for, summary, hero_image, highlights, gallery, is_active) values
  ('full-u-shape', 'The Full U-Shape', '21-piece U-shape — fits 10'' × 13'' × 10'' walls', 'U-Shape', 21, 4800, 'Three walls: 10'' + 13'' + 10''', 120, 156, 120, null, 30, 36, 'Three-walled kitchens, classic family layouts, no-island floor plans.', 'Classic three-wall U-shape with two working corners, a tall pantry, range bay, and fridge bay. Maximum storage for the footprint. 30" range gap left for a chimney hood (not included).', '/images/kits/full-u-shape.jpg', '["Lazy-susan corner + blind base corner \u00e2\u20ac\u201d every inch used", "Tall 24\" \u00c3\u2014 90\" pantry tower", "Two wall diagonal-corner cabinets keep uppers continuous", "30\" range gap with open wall for chimney hood"]'::jsonb, '["/images/kits/full-u-shape.jpg"]'::jsonb, true)
on conflict (slug) do update set name=excluded.name, tagline=excluded.tagline, shape=excluded.shape, pieces=excluded.pieces, price_cad=excluded.price_cad, layout_fits=excluded.layout_fits, wall_a_inches=excluded.wall_a_inches, wall_b_inches=excluded.wall_b_inches, wall_c_inches=excluded.wall_c_inches, island_inches=excluded.island_inches, range_inches=excluded.range_inches, fridge_inches=excluded.fridge_inches, best_for=excluded.best_for, summary=excluded.summary, hero_image=excluded.hero_image, highlights=excluded.highlights, gallery=excluded.gallery, is_active=true, updated_at=now();
delete from public.readykitchens_kit_items where kit_slug='full-u-shape';
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 0, 'LS33', 1, 'Inside corner — sink leg');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 1, 'BBC42-45', 1, 'Inside corner — fridge leg');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 2, 'SB33', 1, 'Wall A — sink');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 3, 'B12', 3, 'Walls A + B — narrow bases');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 4, 'DB18', 2, 'Walls A + B — drawer banks');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 5, 'B24', 1, 'Wall A — end base');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 6, 'B18', 1, 'Wall B — base run');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 7, 'WP249024', 1, 'Wall C — storage tower');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 8, 'B27', 1, 'Wall C — fridge-side end');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 9, 'WDC2436', 2, 'Both wall corners');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 10, 'W3036', 4, 'Main uppers across all walls');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 11, 'W2736', 1, 'Wall C — over end base');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 12, 'W2436', 1, 'Wall A — over end base');
insert into public.readykitchens_kit_items (kit_slug, position, sku, qty, note) values ('full-u-shape', 13, 'W361824', 1, 'Wall C — above fridge');
