export const site = {
  name: "Ontario Light Shows",
  shortName: "Ontario Light Shows",
  phone: "519-878-6735",
  phoneHref: "tel:+15198786735",
  email: "service@masterdecker.com",
  emailHref: "mailto:service@masterdecker.com",
  address: {
    city: "Chatham-Kent",
    region: "ON",
    country: "CA",
  },
  addressLine: "Chatham-Kent, ON · Serving All of Ontario",
  hours: "Mon – Fri · 9 AM – 7 PM | Sat · 10 AM – 4 PM",
  yearsExperience: 8,
  url: "https://ontariolightshows.ca",
  tagline: "Synchronized to Music. Engineered to Last.",
  description:
    "Ontario Light Shows designs and installs high-end music-synchronized addressable LED light shows, RGB architectural lighting, immersive light displays, and permanent holiday lighting with IP67/IP68 rated hardware. Experiential lighting for homes, businesses, and community events across Ontario.",
  serviceAreas: [
    "Toronto",
    "Ottawa",
    "Hamilton",
    "London",
    "Windsor",
    "Chatham-Kent",
    "Mississauga",
    "Kitchener-Waterloo",
  ],
  stats: {
    installations: 240,
    pixelsLit: "1.2M+",
    eventsProduced: 65,
    happyClients: 320,
  },
  serviceCategories: [
    "Experiential Lighting",
    "Architectural Accenting",
    "RGB Architectural Lighting",
    "Immersive Light Displays",
    "Permanent Holiday Lighting",
  ],
  features: [
    "IP67/IP68 rated outdoor-grade hardware",
    "Music-synchronized addressable LED systems",
    "Millions of colours, every pixel independently controlled",
    "Architecturally mounted — invisible by day",
    "Smartphone app + voice control",
    "Multi-year manufacturer warranty",
  ],
  trustBadges: [
    { label: "Live Shows Produced", value: "65+ Events" },
    { label: "Pixels Programmed", value: "1.2M+ LEDs" },
    { label: "Hardware Rating", value: "IP67 / IP68" },
    { label: "Warranty", value: "Multi-Year" },
  ],
  responseTime: "24 hours",
} as const;
