export const site = {
  name: "Restore My Deck",
  tagline: "Restore Your Wood Without Replacement!",
  phone: "226.476.2055",
  phoneHref: "tel:+12264762055",
  email: "service@restoremydeck.ca",
  url: "https://restoremydeck.ca",
  address: {
    city: "Kitchener",
    region: "ON",
    country: "CA",
  },
  hours: "Mon–Fri 8:00 AM – 5:00 PM",
  services: [
    { name: "Deck Restoration", href: "/deck-restoration" },
    { name: "Deck Staining", href: "/deck-staining" },
    { name: "Deck Cleaning", href: "/deck-cleaning" },
    { name: "Deck Power Washing", href: "/deck-power-washing" },
    { name: "Deck Sealing", href: "/deck-sealing" },
    { name: "Deck Sanding", href: "/deck-sanding" },
    { name: "Deck Repair & Maintenance", href: "/deck-repair-and-maintenance" },
    { name: "Deck Rebuilding", href: "/deck-rebuilding" },
    { name: "Fence Cleaning", href: "/fence-cleaning" },
    { name: "Fence Staining", href: "/fence-staining" },
    { name: "Fence Painting", href: "/fence-painting" },
  ],
  serviceAreas: [
    { name: "Kitchener", href: "/kitchener-deck-fence-staining" },
    { name: "Waterloo", href: "/waterloo-deck-fence-staining" },
    { name: "Cambridge", href: "/cambridge-deck-staining" },
    { name: "Guelph", href: "/guelph-deck-fence-staining" },
    { name: "Hamilton", href: "/hamilton-deck-fence-staining" },
    { name: "Stratford", href: "/stratford-deck-staining" },
    { name: "Woodstock", href: "/woodstock-deck-staining" },
    { name: "Fergus", href: "/fergus-deck-staining" },
    { name: "Paris", href: "/paris-deck-staining" },
    { name: "Brantford", href: "/service-areas" },
    { name: "Elmira", href: "/service-areas" },
    { name: "St. Jacobs", href: "/service-areas" },
  ],
};
