export const site = {
  name: "Optimum HVAC",
  phone: "(519) 555-0180",
  phoneHref: "tel:+15195550180",
  email: "info@optimumhvac.ca",
  address: {
    street: "Burgessville",
    city: "Burgessville",
    region: "ON",
    postalCode: "N0J 1C0",
    country: "CA",
  },
  geo: { lat: 43.0178, lon: -80.6549 },
  hours: "Mon – Fri · 8 AM – 6 PM | Sat · 9 AM – 3 PM",
  hoursEmergency: "24/7 Emergency Service Available",
  url: "https://optimumhvac.ca",
  tagline: "Oxford County's TSSA-Certified HVAC Specialists.",
  description:
    "Optimum HVAC delivers expert furnace repair, AC installation, heat pump conversions, and indoor air quality solutions across Oxford County and southwestern Ontario. TSSA G2 certified. 24/7 emergency service.",
  responseTime: "same day",
  serviceAreas: [
    "Burgessville",
    "Woodstock",
    "Ingersoll",
    "Tillsonburg",
    "Norwich",
    "Brantford",
    "Paris",
    "Simcoe",
    "St. Thomas",
    "London",
    "Oakville",
    "Burlington",
  ],
  brands: [
    "Lennox",
    "Carrier",
    "Trane",
    "Goodman",
    "Mitsubishi",
    "Napoleon",
    "Daikin",
    "Ecobee",
    "Navien",
    "Rinnai",
  ],
  certifications: ["TSSA G2", "HRAI Member", "WSIB Clearance", "Fully Insured"],
  gtmId: "GTM-XXXXXXX",
};
