// Sales PDFs for prospects, dealers and installers. The files and their cover
// thumbnails are generated by scripts/build-pdfs.mjs from the same content
// this site renders, so re-run it after any price, kit or warranty change.

export interface Brochure {
  slug: string;
  title: string;
  description: string;
  audience: string;
  pages: number;
  href: string;
  thumb: string;
}

const pdf = (name: string) => `/downloads/forever-lights-${name}.pdf`;
const thumb = (name: string) => `/images/downloads/forever-lights-${name}.webp`;

export const brochures: Brochure[] = [
  {
    slug: 'brochure',
    title: 'The Forever Lights Brochure',
    description: 'The two-page overview: how it works, what goes on your home, how it handles winter, the warranty and starting prices. If you only read one, read this.',
    audience: 'Start here',
    pages: 2,
    href: pdf('brochure'),
    thumb: thumb('brochure'),
  },
  {
    slug: 'seasonal-vs-permanent-cost',
    title: 'Seasonal vs Permanent: The Cost Comparison',
    description: 'Ten years of seasonal Christmas installs against one permanent install, using real prices from our 2025 season, with room to run your own numbers.',
    audience: 'Seasonal Christmas customers',
    pages: 2,
    href: pdf('seasonal-vs-permanent-cost'),
    thumb: thumb('seasonal-vs-permanent-cost'),
  },
  {
    slug: 'pricing-and-packages',
    title: 'Pricing & Packages',
    description: 'All six packages as DIY kits or professionally installed, install options, track colours, monthly financing, and exactly what is in each kit.',
    audience: 'Homeowners & DIY',
    pages: 2,
    href: pdf('pricing-and-packages'),
    thumb: thumb('pricing-and-packages'),
  },
  {
    slug: 'faq',
    title: 'Frequently Asked Questions',
    description: 'Short answers on the look, winter, the app, cost, permits, installation, warranty and what happens if you move.',
    audience: 'Homeowners',
    pages: 2,
    href: pdf('faq'),
    thumb: thumb('faq'),
  },
  {
    slug: 'commercial-and-builders',
    title: 'Commercial & Builders',
    description: 'Brand colours on demand, every site in one app, and per-house pricing for storefronts, plazas, property managers and builders.',
    audience: 'Businesses & builders',
    pages: 1,
    href: pdf('commercial-and-builders'),
    thumb: thumb('commercial-and-builders'),
  },
  {
    slug: 'lookbook',
    title: 'The Lookbook',
    description: 'Homes lit with Forever Lights: invisible by day, warm white every night, and a different colour for every holiday.',
    audience: 'Inspiration',
    pages: 5,
    href: pdf('lookbook'),
    thumb: thumb('lookbook'),
  },
];

export const getBrochure = (slug: string) => brochures.find((b) => b.slug === slug)!;
