export const site = {
  name: "Deck Stainers",
  shortName: "DeckStain",
  phone: "519-914-3387",
  phoneHref: "tel:+15199143387",
  email: "info@deckstain.ca",
  emailHref: "mailto:info@deckstain.ca",
  address: { city: "London", region: "ON", country: "CA" },
  addressLine: "Serving Southwestern Ontario",
  hours: "Mon–Fri · 8 AM – 6 PM | Sat by Appointment",
  url: "https://deckstain.ca",
  tagline: "Ontario's Expert Deck & Fence Staining Specialists",
  description:
    "Professional deck staining, sealing, cleaning, and restoration across Southwestern Ontario. We use READY Seal® oil-based stains for long-lasting results. Free photo-based quotes within 2 business days.",
  serviceAreas: [
    "London",
    "Woodstock",
    "St. Thomas",
    "Stratford",
    "Brantford",
    "Kitchener",
    "Cambridge",
    "Guelph",
    "Tillsonburg",
  ],
  stainBrand: "READY Seal®",
  responseTime: "2 business days",
  stats: {
    projectsCompleted: 500,
    yearsExperience: 8,
    citiesServed: 40,
    satisfactionRate: 100,
  },
  features: [
    "READY Seal® oil-based stains — no peeling, no flaking",
    "Free photo quotes — no in-person visit needed",
    "2-day turnaround on online quote requests",
    "Experienced, friendly team of professionals",
    "Serving 40+ cities across Southwestern Ontario",
    "100% satisfaction guaranteed on every job",
  ],
  trustBadges: [
    { label: "Photo Quotes", value: "2-Day Turnaround" },
    { label: "Projects Done", value: "500+" },
    { label: "Cities Served", value: "40+" },
    { label: "Guarantee", value: "100% Satisfaction" },
  ],
} as const;
