export const site = {
  name: "Classic Christmas Lighting",
  shortName: "Classic",
  tagline: "Professional Christmas Light Installation in Kitchener-Waterloo & Southern Ontario",
  phone: "(226) 476-2038",
  phoneHref: "tel:+12264762038",
  email: "contact@classicchristmaslighting.ca",
  emailHref: "mailto:contact@classicchristmaslighting.ca",
  address: {
    city: "Kitchener",
    region: "ON",
    country: "CA",
  },
  hours: "Mon–Fri: 9 AM–5 PM · Sat: 10 AM–4 PM",
  hoursShort: "Mon–Fri 9–5 · Sat 10–4",
  yearsExperience: 15,
  responseTime: "1 business day",
  serviceAreas: [
    "Kitchener",
    "Waterloo",
    "Cambridge",
    "Guelph",
    "Hamilton",
    "Woodstock",
    "Stratford",
    "Kitchener Surrounding Areas",
  ],
  trustBadges: [
    { label: "15+ Years", value: "Hanging lights in Waterloo Region" },
    { label: "Fully Insured", value: "Crew and property covered" },
    { label: "No Travel Charges", value: "Anywhere in our service area" },
    { label: "Family Owned", value: "Based in Kitchener" },
  ],
  url: "https://classicchristmaslighting.ca",
  facebookUrl: "https://facebook.com/classicchristmaslighting",
  description:
    "Professional Christmas light installation serving Kitchener-Waterloo, Cambridge, Guelph, Hamilton, Woodstock, and Stratford. Family-owned with 15 years of experience. Full installation, maintenance & takedown — no ladders, no stress.",
} as const;
