export const site = {
  name: "Ontario Ramp Solutions",
  shortName: "ORS",
  phone: "(519) 555-0100",
  phoneHref: "tel:+15195550100",
  email: "info@ontariorampsolutions.ca",
  emailHref: "mailto:info@ontariorampsolutions.ca",
  address: {
    city: "London",
    region: "ON",
    country: "CA",
  },
  addressLine: "London, ON · Serving All of Ontario",
  hours: "Mon – Fri · 8 AM – 6 PM | Sat · 9 AM – 3 PM",
  yearsExperience: 10,
  url: "https://ontariorampsolutions.ca",
  tagline: "Accessible. Everywhere. For Everyone.",
  description:
    "Ontario Ramp Solutions provides professional wheelchair ramp installation and rental across Ontario. We build permanent modular ramps for homes and businesses, deliver temporary rental ramps with same-day setup, and specialize in event accessibility for weddings, festivals, and corporate gatherings in London, Hamilton, Kitchener-Waterloo, the GTA, and beyond.",
  serviceAreas: [
    "London",
    "Hamilton",
    "Kitchener-Waterloo",
    "Toronto",
    "Mississauga",
    "Brampton",
    "Burlington",
    "Guelph",
    "Cambridge",
  ],
  stats: {
    rampsInstalled: "500+",
    eventsServed: "200+",
    citiesServed: "40+",
    yearsInBusiness: 10,
  },
  trustBadges: [
    { label: "Ramps Installed", value: "500+" },
    { label: "Events Served", value: "200+" },
    { label: "Cities Across Ontario", value: "40+" },
    { label: "Years of Service", value: "10+" },
  ],
  serviceCategories: [
    "Permanent Ramp Installation",
    "Temporary Ramp Rental",
    "Event Accessibility",
    "Handrail Installation",
  ],
  features: [
    "Aluminum modular ramps — durable, non-slip, weather-resistant",
    "Same-day delivery and setup available",
    "Event specialists for weddings, festivals, and corporate gatherings",
    "Licensed, insured, and AODA-compliant installations",
    "Free on-site consultations across Ontario",
    "Flexible rental terms: daily, weekly, monthly, or long-term",
  ],
  responseTime: "24 hours",
} as const;
