export const site = {
  name: "Christmas Lights London",
  tagline: "Professional Christmas Light Installation in London, ON",
  phone: "(519) 471-1649",
  phoneHref: "tel:+15194711649",
  email: "info@christmaslightslondon.ca",
  emailHref: "mailto:info@christmaslightslondon.ca",
  address: {
    street: "56 Portsmouth Road",
    city: "London",
    region: "ON",
    postal: "N5V 4E2",
    country: "CA",
  },
  addressLine: "56 Portsmouth Road, London, ON N5V 4E2",
  hours: "Monday–Friday · 8:00 AM – 5:00 PM",
  yearsExperience: 5,
  teamSize: 7,
  liftHeight: "30-ft",
  serviceAreas: [
    "London",
    "Kitchener",
    "Hamilton",
    "Mississauga",
    "Brantford",
    "Ancaster",
    "Brampton",
    "Burlington",
    "Cambridge",
    "Chatham",
    "Etobicoke",
    "Georgetown",
    "Guelph",
    "Ingersoll",
    "Milton",
    "Oakville",
    "Sarnia",
    "St. Thomas",
    "Strathroy",
    "Waterloo",
    "Woodstock",
  ],
  url: "https://christmaslightslondon.ca",
  facebookUrl: "https://facebook.com/christmaslightslondon",
  youtubeUrl: "https://youtube.com/@christmaslightslondon",
  description:
    "Professional Christmas light installation in London, Ontario and surrounding areas. Custom-cut lights, aerial lift equipment, no ladders needed. 7-person team with 5+ years experience. Full installation, maintenance, and takedown service.",
} as const;
