export const site = {
  name: "Concrete Driveways",
  shortName: "Concrete Driveways",
  phone: "519-264-5847",
  phoneHref: "tel:+15192645847",
  email: "service@masterdecker.com",
  emailHref: "mailto:service@masterdecker.com",
  address: {
    city: "London",
    region: "ON",
    country: "CA",
  },
  addressLine: "London, ON",
  hours: "Mon – Fri · 7 AM – 6 PM | Sat · 8 AM – 2 PM",
  yearsExperience: 15,
  url: "https://concretedriveways.ca",
  tagline: "Built to Last. Poured to Impress.",
  description:
    "Custom-poured concrete driveways, patios, walkways, and decorative concrete across London, St. Thomas, and Southwestern Ontario. 15+ years of trusted residential concrete work — engineered for Ontario freeze-thaw winters and built with a written warranty.",
  serviceAreas: [
    "London",
    "St. Thomas",
    "Strathroy",
    "Woodstock",
    "Ingersoll",
    "Dorchester",
    "Aylmer",
    "Tillsonburg",
  ],
  stats: {
    drivewaysPoured: 420,
    patiosBuilt: 180,
    happyHomes: 600,
    yearsLifespan: 30,
  },
  finishOptions: ["Broom Finish", "Smooth Trowel", "Exposed Aggregate", "Stamped Pattern", "Coloured Concrete"],
  features: [
    "Written warranty on every pour",
    "Engineered for Ontario freeze-thaw",
    "Reinforced rebar + wire mesh",
    "Proper drainage + grading included",
    "Free on-site quote within 48 hours",
    "Fully insured + WSIB compliant",
  ],
  trustBadges: [
    { label: "Google Reviews", value: "4.9 / 5 Stars" },
    { label: "Years in Business", value: "15+ Years" },
    { label: "Driveways Poured", value: "420+ Projects" },
    { label: "Warranty", value: "Written Guarantee" },
  ],
  responseTime: "4 business hours",
} as const;
