// Stock comes from a monthly snapshot of the Master Decker command center
// (src/content/inventory.json, generated by `node --experimental-sqlite scripts/sync-inventory.mjs`).
// No live database: sales are infrequent, so a monthly refresh + redeploy is enough.

import snapshot from "@/content/inventory.json";

export type StockInfo = {
  on_hand: number;
  on_order: number;
  in_stock: boolean;
  low_stock: boolean;
};

type SnapshotItem = {
  on_hand: number;
  on_order?: number;
  list_price?: number | null;
  lifecycle?: string;
  name?: string;
  on_site?: boolean;
};

type Snapshot = { generatedAt: string; items: Record<string, SnapshotItem> };

const LOW_STOCK_AT = 3;

/** Case/punctuation-insensitive key so catalog SKUs match the command center's spelling. */
export function stockKey(sku: string): string {
  return sku.toUpperCase().replace(/×/g, "X").replace(/[^A-Z0-9]/g, "");
}

let cached: Record<string, StockInfo> | null = null;

/** Synchronous map keyed by stockKey(). Usable in server and client code (the JSON is tiny). */
export function inventoryMap(): Record<string, StockInfo> {
  if (cached) return cached;
  const out: Record<string, StockInfo> = {};
  for (const [sku, it] of Object.entries((snapshot as Snapshot).items)) {
    // Items the command center only proposes (e.g. the 30" wall line) aren't stocked yet.
    if (it.lifecycle && it.lifecycle !== "stocked") continue;
    const on_hand = Math.max(0, it.on_hand ?? 0);
    out[stockKey(sku)] = {
      on_hand,
      on_order: Math.max(0, it.on_order ?? 0),
      in_stock: on_hand > 0,
      low_stock: on_hand > 0 && on_hand <= LOW_STOCK_AT,
    };
  }
  cached = out;
  return out;
}

/** When the snapshot was last pulled from the command center. */
export function inventoryUpdatedAt(): Date {
  return new Date((snapshot as Snapshot).generatedAt);
}

export async function getInventoryMap(): Promise<Record<string, StockInfo>> {
  return inventoryMap();
}

export function getStockSync(sku: string): StockInfo | undefined {
  return inventoryMap()[stockKey(sku)];
}

export async function getStockForSku(sku: string): Promise<StockInfo | undefined> {
  return getStockSync(sku);
}

/** Re-key an inventory map by the catalog's own SKUs so client code can look up directly. */
export function mapForSkus(map: Record<string, StockInfo>, skus: string[]): Record<string, StockInfo> {
  const out: Record<string, StockInfo> = {};
  for (const sku of skus) {
    const s = map[stockKey(sku)];
    if (s) out[sku] = s;
  }
  return out;
}
