export const site = {
  name: "Celebrate Lighting",
  tagline: "Permanent Outdoor LED Lighting in Ontario",
  phone: "1-833-243-3068",
  phoneHref: "tel:+18332433068",
  email: "contact@celebratelighting.ca",
  emailHref: "mailto:contact@celebratelighting.ca",
  address: {
    street: "631 Peel Street",
    city: "Woodstock",
    region: "ON",
    postal: "N4S 1K1",
    country: "CA",
  },
  addressLine: "631 Peel Street, Woodstock, ON",
  hours: "Mon–Fri 8 AM–8 PM · Sat 9 AM–6 PM · Sun 10 AM–4 PM",
  hoursDetailed: [
    { day: "Monday – Friday", hours: "8:00 AM – 8:00 PM" },
    { day: "Saturday", hours: "9:00 AM – 6:00 PM" },
    { day: "Sunday", hours: "10:00 AM – 4:00 PM" },
  ],
  serviceAreas: [
    "St. Thomas",
    "London",
    "Stratford",
    "Brantford",
    "Tillsonburg",
    "Waterloo",
    "Guelph",
    "Woodstock",
  ],
  url: "https://celebratelighting.ca",
  instagram: "https://www.instagram.com/celebratelighting/",
  responseTime: "24 hours",
  yearsExperience: 5,
  warrantyYears: 25,
  trustBadges: [
    { label: "Licensed & Insured", value: "Fully Certified" },
    { label: "Lifetime Warranty", value: "All Installations" },
    { label: "LED Lifespan", value: "50,000+ Hours" },
    { label: "Service Area", value: "SW Ontario" },
  ],
} as const;
