export const site = {
  name: "London Fence Installer",
  shortName: "LFI",
  phone: "519.914.1909",
  phoneHref: "tel:+15199141909",
  email: "info@londonfenceinstaller.ca",
  emailHref: "mailto:info@londonfenceinstaller.ca",
  address: {
    street: "84 Dartmouth Drive",
    city: "London",
    region: "ON",
    country: "CA",
    postalCode: "N5Z 3T7",
  },
  addressLine: "84 Dartmouth Drive, London, Ontario",
  hours: "Mon – Fri · 8 AM – 6 PM",
  yearsExperience: 20,
  url: "https://londonfenceinstaller.ca",
  tagline: "Friendly, Quick, and Professional Fences",
  description:
    "London's trusted fence contractors for wood, vinyl, chainlink, metal fences and more. Fast quotes within 48 hours, 5-year warranty, and 20 years of combined experience serving London, St Thomas, Woodstock, and surrounding areas.",
  serviceAreas: [
    "London",
    "St. Thomas",
    "Woodstock",
    "Aylmer",
    "Strathroy",
    "Tillsonburg",
    "St. Marys",
    "Ingersoll",
    "Dorchester",
    "Thamesford",
  ],
  services: [
    { label: "Wood Fence Contractor", href: "/wood-fencing-contractor" },
    { label: "Chainlink Fencing", href: "/chainlink-fencing" },
    { label: "Vinyl Fence Installation", href: "/vinyl-fence-installation" },
    { label: "Metal Fence Installation", href: "/metal-fence-installation" },
    { label: "Fence Repair", href: "/fence-repair" },
    { label: "Noise Wall & Highway Fencing", href: "/noise-wall-and-highway-fencing" },
    { label: "Guardrail Installation", href: "/guardrail-installation" },
    { label: "Fence Staining", href: "/fence-staining" },
    { label: "Black Aluminum Fencing", href: "/black-aluminum-fencing" },
  ],
  trustBadges: [
    { label: "Free Quotes", value: "Within 48 Hrs" },
    { label: "Warranty", value: "5-Year Limited" },
    { label: "Experience", value: "20 Years Combined" },
    { label: "Coverage", value: "London & Surrounding" },
  ],
  social: {
    facebook: "https://www.facebook.com/londonfenceinstaller",
    twitter: "https://twitter.com/londonfenceinstaller",
    linkedin: "https://www.linkedin.com/company/london-fence-installer",
  },
} as const;
