import Link from "next/link";
import { createKit } from "@/lib/ready-kitchens/actions";

export default function NewKitPage() {
  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <nav className="text-sm text-slate-500">
        <Link href="/ready-kitchens/kits" className="hover:underline">Kits</Link>
        <span className="mx-2">/</span>
        <span className="text-slate-900">New kit</span>
      </nav>
      <h1 className="text-2xl font-semibold">Create a new kit package</h1>
      <p className="text-sm text-slate-500">
        Set the basics here. After saving, you&rsquo;ll be taken to the kit page where you can add cabinets and see live profit/markup calculations.
      </p>

      <form action={createKit} className="space-y-3 rounded-lg border border-slate-200 bg-white p-6">
        <Field label="Kit name" name="name" required placeholder="The Modern Symmetrical" />
        <Field label="Slug (optional — autogenerated)" name="slug" placeholder="modern-symmetrical" />
        <Field label="Tagline" name="tagline" placeholder="16-piece galley kitchen — fits two 10' runs" />
        <div className="grid grid-cols-2 gap-3">
          <Field label="Shape" name="shape" placeholder="Galley / L-Shape / U-Shape / Single Wall / Island" />
          <Field label="Sell price (CAD)" name="price_cad" type="number" required placeholder="3900" />
        </div>
        <Field label="Layout fits" name="layout_fits" placeholder="Two opposing 10-foot walls" />
        <div>
          <label className="block text-xs font-medium text-slate-500">Summary</label>
          <textarea name="summary" rows={3} className="mt-1 w-full rounded border border-slate-300 px-2 py-1.5 text-sm" />
        </div>
        <div>
          <label className="block text-xs font-medium text-slate-500">Best for</label>
          <textarea name="best_for" rows={2} className="mt-1 w-full rounded border border-slate-300 px-2 py-1.5 text-sm" />
        </div>
        <button type="submit" className="rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700">
          Create kit
        </button>
      </form>
    </div>
  );
}

function Field({ label, name, type = "text", required, placeholder }: { label: string; name: string; type?: string; required?: boolean; placeholder?: string }) {
  return (
    <div>
      <label className="block text-xs font-medium text-slate-500" htmlFor={name}>{label}</label>
      <input id={name} name={name} type={type} required={required} placeholder={placeholder} className="mt-1 w-full rounded border border-slate-300 px-2 py-1.5 text-sm" />
    </div>
  );
}
