export const site = {
  name: "London Retaining Walls",
  tagline: "Professional Retaining Wall Installation & Repair in London, Ontario",
  phone: "519-914-1908",
  phoneHref: "tel:+15199141908",
  email: "info@londonretainingwalls.ca",
  url: "https://londonretainingwalls.ca",
  address: {
    city: "London",
    region: "ON",
    country: "CA",
  },
  hours: "Monday – Saturday: 7 AM – 6 PM",
  services: [
    { name: "Retaining Wall Installation", href: "/retaining-wall-installation" },
    { name: "Concrete Retaining Walls", href: "/concrete-retaining-walls" },
    { name: "Block Retaining Walls", href: "/block-retaining-walls" },
    { name: "Wood & Timber Retaining Walls", href: "/wood-and-timber-retaining-walls" },
    { name: "Retaining Wall Repair", href: "/retaining-wall-repair" },
  ],
  serviceAreas: [
    { name: "London", href: "/london-retaining-wall-contractor" },
    { name: "Woodstock", href: "/woodstock-retaining-wall-contractor" },
    { name: "Brantford", href: "/brantford-retaining-wall-contractor" },
    { name: "St. Thomas", href: "/st-thomas-retaining-wall-contractor" },
    { name: "Strathroy", href: "/strathroy-retaining-wall-contractor" },
    { name: "Dorchester", href: "/dorchester-retaining-wall-contractor" },
    { name: "Aylmer", href: "/aylmer-retaining-wall-contractor" },
    { name: "Ilderton", href: "/ilderton-retaining-wall-contractor" },
    { name: "Komoka", href: "/komoka-retaining-wall-contractor" },
    { name: "Mount Brydges", href: "/mount-brydges-retaining-wall-contractor" },
    { name: "Lucan", href: "/lucan-retaining-wall-contractor" },
    { name: "Delaware", href: "/delaware-retaining-wall-contractor" },
  ],
};
