export const site = {
  name: "Legal Basements London",
  phone: "519-266-6796",
  phoneHref: "tel:+15192666796",
  email: "service@masterdecker.com",
  address: {
    city: "London",
    region: "ON",
    country: "CA",
  },
  hours: "Mon – Fri · 7 AM – 6 PM | Sat · 8 AM – 2 PM",
  yearsExperience: 15,
  url: "https://getlegalbasements.ca",
  tagline: "Make Your Basement Legal. Add Value. Generate Income.",
  description:
    "London Ontario’s trusted experts in legal basement apartments, second suites, underpinning, waterproofing, and full basement renovations. We handle permits, design, and construction so you can maximize your property’s potential.",
  serviceAreas: [
    "London",
    "St. Thomas",
    "Woodstock",
    "Strathroy",
    "Tillsonburg",
    "Ingersoll",
    "Aylmer",
    "Dorchester",
    "Komoka",
    "Lucan",
  ],
  features: [
    "Full permit handling and code compliance",
    "Licensed and insured general contractor",
    "End-to-end project management",
    "3D design renderings before construction",
    "Fixed pricing with no hidden fees",
    "2-year workmanship warranty",
    "Free consultations and site assessments",
    "Financing options available",
  ],
} as const;
